openapi: 3.2.0
info:
  title: Raw Export API
  version: ''
  description: This asynchronous API enables export of user & event data from CrossEngage.
servers:
- url: https://api.crossengage.io/
tags:
- name: Export
paths:
  /export:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: array
                items: {}
              example:
              - status: WAITING
                requestedAt: '2019-09-04T15:30:53.298Z'
                startedAt: '2019-09-04T15:36:53.298Z'
                finishedAt: '2019-09-04T15:37:53.298Z'
                id: 1ee25bc0-21aa-4759-8716-8397b6997e98
                exportDestinationId: fec9ce18-a152-4fec-ab69-1b22606a015e
                callbackDestinationId: 4ce5fad8-4ec6-41ad-a5a0-fbf9b9ebdde0
                rawExport: true
                outputFormat: PARQUET
                outputSuffix: PARQUET
                segmentId: '67'
                attributes:
                  enabled: true
                  filter:
                    action: INCLUDE
                    names:
                    - traits.firstName
                    - traits.lastName
                    - traits.email
                events:
                  enabled: false
      summary: Get all exports and their details
      operationId: Get all exports and their details
      description: ''
      tags:
      - Export
      parameters:
      - name: status
        in: query
        description: _Optional_. Export status filter. By default only active exports are returned (`WAITING` and `RUNNING`)
        required: false
        x-example: FINISHED
        schema:
          type: string
          enum:
          - WAITING
          - RUNNING
          - FINISHED
          - CANCELED
      - name: pageNumber
        in: query
        description: _Optional_. page number.
        required: false
        x-example: '3'
        schema:
          type: integer
      - name: pageSize
        in: query
        description: _Optional_. page size.
        required: false
        x-example: '25'
        schema:
          type: integer
          default: 10
      - name: X-XNG-ApiVersion
        in: header
        description: e.g. 2
        required: false
        x-example: '2'
        schema:
          type: string
      - name: X-XNG-AuthToken
        in: header
        description: e.g. YourAPIKey
        required: false
        x-example: YourAPIKey
        schema:
          type: string
    post:
      responses:
        '200':
          description: Export job scheduled.
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                    - WAITING
                    - RUNNING
                    - FINISHED
                    - CANCELED
                    description: Status of an export.
                  requestedAt:
                    type: string
                    description: ISO 8601 formatted string representing the export request date and time.
                  startedAt:
                    type: string
                    description: ISO 8601 formatted string representing the export start date and time.
                  finishedAt:
                    type: string
                    description: ISO 8601 formatted string representing the export finish date and time.
                  id:
                    type: string
                    description: ID of a requested export.
                  exportDestinationId:
                    type: string
                    description: _Required_. ID of a destination used for saving the export data.
                  callbackDestinationId:
                    type: string
                    description: _Optional_. ID of a destination used to send callback notifications generated by the export job. When not provided no callbacks will be sent.
                  rawExport:
                    type: boolean
                  outputFormat:
                    type: string
                    description: _Optional_. This allows defining the export data format(PARQUET or JSON) defaults to JSON.
                  outputSuffix:
                    type: string
                    description: _Optional_. String that will be appended to the File-Name.
                  segmentId:
                    type: string
                    description: _Optional_. ID of a user segment to be exported. When not provided all users will be exported. Please note that providing a segment will add an additional filtering step, which can slow down your export.
                  attributes:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        description: _Optional_. This toggles attribute data export. When not provided takes default value `false` so that attributes will not be exported.
                      filter:
                        type: object
                        properties:
                          action:
                            type: string
                            enum:
                            - INCLUDE
                            - EXCLUDE
                            description: _Required_. Action to be done using the names array. Required when using the `filter` object.
                          names:
                            type: array
                            description: _Required_. User attribute names that will be used together with the action for the export.
                            items: {}
                        required:
                        - action
                        - names
                        description: _Optional_. The `filter` object allows you to include or exclude certain attributes from the export. When not provided, all user attribute data will be exported.
                    description: _Required_. Export settings for user attributes. Can not be used in conjuction with the `events` object.
                  events:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        description: _Optional_. When not provided takes default value `false` as events will not be exported with the raw user export.
                    description: _Required_. Export settings for event data. Can be used in conjunction with the `attributes` object.
                required:
                - exportDestinationId
                - rawExport
                - attributes
                - events
              example:
                status: WAITING
                requestedAt: '2019-09-04T15:30:53.298Z'
                startedAt: '2019-09-04T15:36:53.298Z'
                finishedAt: '2019-09-04T15:37:53.298Z'
                id: 1ee25bc0-21aa-4759-8716-8397b6997e98
                exportDestinationId: fec9ce18-a152-4fec-ab69-1b22606a015e
                callbackDestinationId: 4ce5fad8-4ec6-41ad-a5a0-fbf9b9ebdde0
                rawExport: true
                outputFormat: PARQUET
                outputSuffix: PARQUET
                segmentId: '67'
                attributes:
                  enabled: true
                  filter:
                    action: INCLUDE
                    names:
                    - traits.firstName
                    - traits.lastName
                    - traits.email
                events:
                  enabled: false
      summary: Request an export(users)
      operationId: Request an export(users)
      description: ''
      tags:
      - Export
      parameters:
      - name: X-XNG-ApiVersion
        in: header
        description: e.g. 2
        required: false
        x-example: '2'
        schema:
          type: string
      - name: X-XNG-AuthToken
        in: header
        description: e.g. YourAPIKey
        required: false
        x-example: YourAPIKey
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userExportRequest'
  /export/{exportId}:
    get:
      responses:
        '200':
          description: Export details and status.
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                    - WAITING
                    - RUNNING
                    - FINISHED
                    - CANCELED
                    description: Status of an export.
                  requestedAt:
                    type: string
                    description: ISO 8601 formatted string representing the export request date and time.
                  startedAt:
                    type: string
                    description: ISO 8601 formatted string representing the export start date and time.
                  finishedAt:
                    type: string
                    description: ISO 8601 formatted string representing the export finish date and time.
                  id:
                    type: string
                    description: ID of a requested export.
                  exportDestinationId:
                    type: string
                    description: _Required_. ID of a destination used for saving the export data.
                  callbackDestinationId:
                    type: string
                    description: _Optional_. ID of a destination used to send callback notifications generated by the export job. When not provided no callbacks will be sent.
                  rawExport:
                    type: boolean
                  outputFormat:
                    type: string
                    description: _Optional_. This allows defining the export data format(PARQUET or JSON) defaults to JSON.
                  outputSuffix:
                    type: string
                    description: _Optional_. String that will be appended to the File-Name.
                  segmentId:
                    type: string
                    description: _Optional_. ID of a user segment to be exported. When not provided all users will be exported. Please note that providing a segment will add an additional filtering step, which can slow down your export.
                  attributes:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        description: _Optional_. This toggles attribute data export. When not provided takes default value `false` so that attributes will not be exported.
                      filter:
                        type: object
                        properties:
                          action:
                            type: string
                            enum:
                            - INCLUDE
                            - EXCLUDE
                            description: _Required_. Action to be done using the names array. Required when using the `filter` object.
                          names:
                            type: array
                            description: _Required_. User attribute names that will be used together with the action for the export.
                            items: {}
                        required:
                        - action
                        - names
                        description: _Optional_. The `filter` object allows you to include or exclude certain attributes from the export. When not provided, all user attribute data will be exported.
                    description: _Required_. Export settings for user attributes. Can not be used in conjuction with the `events` object.
                  events:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        description: _Optional_. When not provided takes default value `false` as events will not be exported with the raw user export.
                    description: _Required_. Export settings for event data. Can be used in conjunction with the `attributes` object.
                required:
                - exportDestinationId
                - rawExport
                - attributes
                - events
              example:
                status: WAITING
                requestedAt: '2019-09-04T15:30:53.298Z'
                startedAt: '2019-09-04T15:36:53.298Z'
                finishedAt: '2019-09-04T15:37:53.298Z'
                id: 1ee25bc0-21aa-4759-8716-8397b6997e98
                exportDestinationId: fec9ce18-a152-4fec-ab69-1b22606a015e
                callbackDestinationId: 4ce5fad8-4ec6-41ad-a5a0-fbf9b9ebdde0
                rawExport: true
                outputFormat: PARQUET
                outputSuffix: PARQUET
                segmentId: '67'
                attributes:
                  enabled: true
                  filter:
                    action: INCLUDE
                    names:
                    - traits.firstName
                    - traits.lastName
                    - traits.email
                events:
                  enabled: false
      summary: Get a certain export's details
      operationId: Get a certain export's details
      description: ''
      tags:
      - Export
      parameters:
      - name: exportId
        in: path
        description: _Required_. `id` of an export
        required: true
        x-example: 1ee25bc0-21aa-4759-8716-8397b6997e98
        schema:
          type: string
      - name: X-XNG-ApiVersion
        in: header
        description: e.g. 2
        required: false
        x-example: '2'
        schema:
          type: string
      - name: X-XNG-AuthToken
        in: header
        description: e.g. YourAPIKey
        required: false
        x-example: YourAPIKey
        schema:
          type: string
    delete:
      responses:
        '200':
          description: Export job stopped.
          headers: {}
          content: {}
      summary: Cancel an export
      operationId: Cancel an export
      description: ''
      tags:
      - Export
      parameters:
      - name: exportId
        in: path
        description: _Required_. `id` of an export
        required: true
        x-example: 1ee25bc0-21aa-4759-8716-8397b6997e98
        schema:
          type: string
      - name: X-XNG-ApiVersion
        in: header
        description: e.g. 2
        required: false
        x-example: '2'
        schema:
          type: string
      - name: X-XNG-AuthToken
        in: header
        description: e.g. YourAPIKey
        required: false
        x-example: YourAPIKey
        schema:
          type: string
components:
  schemas:
    userExportRequest:
      type: object
      required:
      - exportDestinationId
      - rawExport
      - attributes
      - events
      properties:
        exportDestinationId:
          type: string
          example: fec9ce18-a152-4fec-ab69-1b22606a015e
          description: _Required_. ID of a destination used for saving the export data.
        callbackDestinationId:
          type: string
          example: 4ce5fad8-4ec6-41ad-a5a0-fbf9b9ebdde0
          description: _Optional_. ID of a destination used to send callback notifications generated by the export job. When not provided no callbacks will be sent.
        rawExport:
          type: boolean
          example: true
        outputFormat:
          type: string
          example: PARQUET
          description: _Optional_. This allows defining the export data format(PARQUET or JSON) defaults to JSON.
        outputSuffix:
          type: string
          example: PARQUET
          description: _Optional_. String that will be appended to the File-Name.
        segmentId:
          type: string
          example: '67'
          description: _Optional_. ID of a user segment to be exported. When not provided all users will be exported. Please note that providing a segment will add an additional filtering step, which can slow down your export.
        attributes:
          type: object
          properties:
            enabled:
              type: boolean
              example: true
              description: _Optional_. This toggles attribute data export. When not provided takes default value `false` so that attributes will not be exported.
            filter:
              type: object
              required:
              - action
              - names
              properties:
                action:
                  type: string
                  enum:
                  - INCLUDE
                  - EXCLUDE
                  description: _Required_. Action to be done using the names array. Required when using the `filter` object.
                names:
                  type: array
                  items: {}
                  description: _Required_. User attribute names that will be used together with the action for the export.
              description: _Optional_. The `filter` object allows you to include or exclude certain attributes from the export. When not provided, all user attribute data will be exported.
          description: _Required_. Export settings for user attributes. Can not be used in conjuction with the `events` object.
        events:
          type: object
          properties:
            enabled:
              type: boolean
              description: _Optional_. When not provided takes default value `false` as events will not be exported with the raw user export.
          description: _Required_. Export settings for event data. Can be used in conjunction with the `attributes` object.
